server:
  port: 8001
spring:
  application:
    name: short-link-project
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: short-link
    listener:
      simple:
        acknowledge-mode: manual          # 手动确认
        retry:
          enabled: true                   # 开启重试
          max-attempts: 3                  # 最大重试次数
          initial-interval: 1000            # 重试间隔


short-link:
  stats:
    locale:
      amap-key: 956be1236b9d4f2011a8fd5c50c082a0
  domain:
    default: zcdada.ink:8001
  goto-domain:
    white-list:
      enable: true
      names: '拿个offer,知乎,掘金,博客园,deepseek'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com
        - deepseek.com


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
